services:
  mongo:
    image: mongo:5
    container_name: mymoney-mongo
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "${API_PORT}:3003"
    environment:
      - PORT=${API_PORT}
      - MONGO_URL=mongodb://mongo:27017/mymoney
      - AUTH_SECRET=change-me
    depends_on:
      - mongo

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    restart: unless-stopped
    ports:
      - "${UI_PORT}:8080"
    environment:
      - REACT_APP_API=http://localhost:3003

volumes:
  mongo_data:


